---
title: ""
author: Ben Marwick
date: Thursday, June 26, 2014
output: html_document
---

# Supplementary details supporting the analysis of shells from the 1989 excavations at Madjebebe (Malakanunja II)

```{r, message=FALSE, echo=FALSE}
# This is necessary to direct knitr to find the 
# 'code', 'data', and other directories that contain
# files needed to execute this document
knitr::opts_knit$set(root.dir=normalizePath('../'))
```


```{r load-data}

shells <- read.csv("data/Shell_table_from_paper_on_1989_dig.csv", header=TRUE, stringsAsFactors = FALSE)
# check that dependencies are locally available
# source("code/packrat.r")
suppressMessages(source("code/libraries.R"))
```



```{r plot-shells}
# edit colnames
shells$`P. coaxans` <- shells$Geloina
shells$`T. telescopium` <- shells$Telescopium
shells$`Cerithidea sp.` <- shells$Cerithidea
shells$`Nerita sp.` <- shells$Nerita

# filter rows
shells <- shells[shells$Spit %in% c("DE30/4", "DE30/5", "DE30/6", "DE30/7", "DE30/8"),]

# add in missing row (read from excel chart embedded in draft)
shells <- rbind(shells, c("DE30/7", 589.2,  113.5, 
             0, 0, 0,
             62, 0, 0,
             0, 292, 113.5,
             589.2, 62))

# subset just certain species
shells <- shells[, c("Spit", "P. coaxans", "T. telescopium", "Cerithidea sp.", "Nerita sp.")]

# sort by spit
shells <- shells[with(shells, order(gsub("[[:alpha:]]", "", shells$Spit)  )), ]

# reshape
library(reshape2)
shells_m <- melt(shells, id = 'Spit')
shells_m$value  <- as.numeric(shells_m$value)

# plot mass
library(ggplot2)
plot_mass <- ggplot(shells_m, aes(Spit, value)) +
  geom_bar(aes(fill = variable), position = "dodge", stat="identity") +
  theme_minimal(base_size = 12) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5)) +
  ylab("Mass (g)") +
  xlab("Square and spit") +
  scale_fill_discrete(name="Taxon") +
  theme(aspect.ratio = 1) 
  

# compute percent of spit total
shells[, c("P. coaxans", "T. telescopium", "Cerithidea sp.", "Nerita sp.")] <- sapply(shells[, c("P. coaxans", "T. telescopium", "Cerithidea sp.", "Nerita sp.")], as.numeric)

spit_total <- unname(rowSums(shells[, c("P. coaxans", "T. telescopium", "Cerithidea sp.", "Nerita sp.")], na.rm = TRUE))

shells_perc <- shells[, c("P. coaxans", "T. telescopium", "Cerithidea sp.", "Nerita sp.")]

# compute percentages
df <- shells_perc
for(i in 1:nrow(shells_perc)){
  df[i,] <- shells_perc[i,] / spit_total[i] * 100  
}

df$Spit <- shells$Spit
library(reshape2)
df_m <- melt(df, id = 'Spit')
df_m$value  <- as.numeric(df_m$value)

# plot mass %
plot_perc <- ggplot(df_m, aes(Spit, value)) +
  geom_bar(aes(fill = variable), position = "dodge", stat="identity") +
  theme_minimal(base_size = 12) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5)) +
  ylab("Percentage mass") +
  xlab("Square and spit") +
  scale_fill_discrete(name="Taxon") +
  theme(aspect.ratio = 1)
```


```{r draw-plot}

# plot side by side
require(gridExtra)
plot1 <- plot_mass  # + guides(fill=FALSE)
plot2 <- plot_perc
grid.arrange(plot1, plot2, ncol=2)
# save plot as SVG for finessing...
ggsave(file = "figures/shell_from_1989_for_paper.svg")
```


```{r early-attempt, echo = FALSE, eval = FALSE}
# exclude 'total' and comments
shells <- shells[-(9:10),]

# separate squares and spits
units <- unlist(strsplit(shells$Spit, "/")) 
square <- units[seq(1, length(units), 2)] 
spit <- units[seq(2, length(units), 2)]
shells$square <- square
shells$spit <- spit
# have a look at the data
shells
# clean it up a little, delete unwanted columns
shells <- shells[,c(-1,-9,-10)]
# we can see that DE30 has the longest sequence of spits,
# so let's focus on that
DE30 <- shells[shells$square == "DE30",]
# remove square and spit names
DE30 <- DE30[,c(-8:-9)]
# convert numbers to numeric
DE30 <- sapply(DE30, as.numeric)
DE30[is.na(DE30)] <- 0 
# convert to proportions of totals for each species
DE30_prop_spit <- prop.table(as.matrix(DE30), margin=2)*100
# convert to proportions of totals for each spit
DE30_prop_spec <- prop.table(as.matrix(DE30), margin=1)*100
```

```{r reshape-plot,echo = FALSE, eval = FALSE}
library(reshape2)
DE30_prop_spit_m <- melt(DE30_prop_spit, id = row.names)
DE30_prop_spec_m <- melt(DE30_prop_spec, id = row.names)
# plot 
library(ggplot2)
library(scales)
ggplot(data = DE30_prop_spec_m, aes(x = factor(Var1), y = value, fill = factor(Var2))) + 
  geom_bar(stat="identity", position = 'dodge')
ggplot(data = DE30_prop_spec_m, aes(Var2, value)) + 
  geom_bar(stat="identity") + 
  facet_grid(. ~ Var1 ) 

```

